name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write

env:
  host: ${{ secrets.AKENEO_HOST }}
  clientid: ${{ secrets.AKENEO_CLIENT_ID }}
  secret: ${{ secrets.AKENEO_CLIENT_SECRET }}
  user: ${{ secrets.AKENEO_USERNAME }}
  passwd: ${{ secrets.AKENEO_PASSWORD }}
  cdnurl: ${{ secrets.CDN_URL }}
  path: "../docs/"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- name: Configure Git Credentials
      #  run: |
      #    git config user.name github-actions[bot]
      #    git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-committers-plugin-2
      - run: pip install -i https://test.pypi.org/simple/ contentdeskopendata
      - run: contentdeskopendata.ContentdeskOpenData(${{ env.host }}, ${{ env.clientid }}, ${{ env.secret }}, ${{ env.user }}, ${{ env.passwd }}, ${{ env.cdnurl }}, ${{ env.path }})
      #- run: pip install mkdocs-git-authors-plugin
      - name: Create CNAME file
        run: echo "opendata.demo.contentdesk.io" > ./docs/CNAME
      - run: mkdocs gh-deploy --force